"""Central terminology system (spec §13, §51).

One canonical Arabic term per English term. `lesson` points to the full
lesson when one exists; the validator checks it. Categories:
data | math | model | training | evaluation | frameworks | general
"""

from core.models import Term

TERMS: list[Term] = [
    # ---------------------------------------------------------------- general
    Term("artificial_intelligence", "الذكاء الاصطناعي", "Artificial Intelligence (AI)",
         "أي نظام حاسوبي يؤدي مهمة نعدّها تحتاج إلى ذكاء بشري، سواء تعلم من البيانات أم لا.",
         "general", lesson="foundations.start.ai_ml_dl", related=["machine_learning", "deep_learning"]),
    Term("machine_learning", "التعلم الآلي", "Machine Learning (ML)",
         "فرع من الذكاء الاصطناعي تُستخرج فيه القواعد (النموذج) من البيانات بدل كتابتها يدويًا.",
         "general", lesson="foundations.start.ai_ml_dl", related=["artificial_intelligence", "deep_learning", "model"]),
    Term("deep_learning", "التعلم العميق", "Deep Learning (DL)",
         "فرع من التعلم الآلي يستخدم شبكات عصبية متعددة الطبقات تتعلم التمثيلات تلقائيًا.",
         "general", lesson="foundations.start.ai_ml_dl", related=["machine_learning"]),
    Term("model", "النموذج", "Model",
         "دالة ذات معلمات قابلة للتعديل تحوّل مدخلًا إلى تنبؤ.",
         "model", lesson="foundations.start.model_training_prediction", related=["parameter", "training", "prediction"],
         notation=r"\hat{y} = f_\theta(x)"),
    Term("parameter", "المعلمة", "Parameter",
         "قيمة داخل النموذج يتعلمها التدريب، مثل الوزن والانحياز.",
         "model", lesson="foundations.start.model_training_prediction", related=["weight", "bias", "hyperparameter"],
         notation=r"\theta"),
    Term("hyperparameter", "المعلمة الفائقة", "Hyperparameter",
         "قيمة يحددها الباحث قبل التدريب ولا يتعلمها النموذج، مثل معدل التعلم وحجم الدفعة وعدد الطبقات.",
         "training", lesson="foundations.start.model_training_prediction", related=["parameter", "learning_rate", "batch_size"]),
    Term("training", "التدريب", "Training",
         "عملية البحث عن قيم المعلمات التي تقلل الخسارة على بيانات التدريب.",
         "training", lesson="foundations.start.model_training_prediction", related=["loss", "gradient", "optimizer"]),
    Term("prediction", "التنبؤ", "Prediction",
         "مخرج النموذج لمدخل معين.", "model", lesson="foundations.start.model_training_prediction",
         related=["inference"], notation=r"\hat{y}"),
    Term("inference", "الاستدلال", "Inference",
         "مرحلة استخدام النموذج المدرَّب بمعلمات مجمّدة على مدخلات جديدة.",
         "model", lesson="foundations.start.model_training_prediction", related=["prediction", "training"]),
    Term("weight", "الوزن", "Weight",
         "معلمة تضرب مدخلًا وتحدد أهميته واتجاه أثره.", "model",
         lesson="foundations.start.model_training_prediction", related=["bias", "parameter"], notation="w"),
    Term("bias", "الانحياز (الإزاحة)", "Bias",
         "معلمة تُضاف إلى المجموع الموزون لإزاحة المخرج. (لا تخلط مع الانحياز الإحصائي Bias في التعميم.)",
         "model", lesson="foundations.start.model_training_prediction", related=["weight"], notation="b"),
    Term("loss", "الخسارة", "Loss",
         "رقم يقيس سوء تنبؤات النموذج؛ التدريب يقلّله. مثال: متوسط مربع الخطأ.",
         "training", lesson="foundations.start.model_training_prediction", related=["gradient", "training"], notation="L"),
    Term("gradient", "التدرج", "Gradient",
         "متجه المشتقات الجزئية للخسارة بالنسبة لكل معلمة؛ يحدد اتجاه أسرع زيادة للخسارة.",
         "math", lesson="foundations.start.why_data_math_optimization", related=["loss", "learning_rate"],
         notation=r"\nabla_\theta L"),
    Term("learning_rate", "معدل التعلم", "Learning Rate",
         "معلمة فائقة تحدد حجم خطوة تحديث المعلمات في اتجاه عكس التدرج.",
         "training", lesson="foundations.start.why_data_math_optimization", related=["gradient", "optimizer"], notation=r"\eta"),
    Term("optimizer", "المحسّن", "Optimizer",
         "الخوارزمية التي تستخدم التدرج لتحديث المعلمات (SGD، Momentum، RMSprop، Adam).",
         "training", lesson="foundations.start.why_data_math_optimization", related=["gradient", "learning_rate"]),
    # ------------------------------------------------------------------- data
    Term("data", "البيانات", "Data",
         "قياسات أو تسجيلات عن كيانات من العالم.", "data", lesson="foundations.data.what_is_data",
         related=["dataset"]),
    Term("dataset", "مجموعة البيانات", "Dataset",
         "مجموعة من الملاحظات لها نفس الأعمدة (نفس البنية).", "data", lesson="foundations.data.dataset",
         related=["observation", "feature", "target"]),
    Term("observation", "الملاحظة", "Observation (Sample, Instance, Example, Row)",
         "صف واحد في مجموعة البيانات: كيان واحد بقيم جميع قياساته.", "data",
         lesson="foundations.data.observation", related=["dataset", "feature"],
         aliases_ar=["عينة", "مثال", "حالة", "سجل"]),
    Term("feature", "الخاصية", "Feature (Predictor, Independent Variable, Input)",
         "عمود مدخل يصف الملاحظة ويستخدمه النموذج للتنبؤ.", "data", lesson="foundations.data.feature",
         related=["target", "observation"], aliases_ar=["متغير مستقل", "متغير تفسيري", "مدخل"], notation="x"),
    Term("target", "الهدف", "Target (Label, Response, Output)",
         "العمود الذي نريد التنبؤ به.", "data", lesson="foundations.data.target",
         related=["feature"], aliases_ar=["تسمية", "استجابة", "متغير تابع", "مخرج"], notation="y"),
    Term("categorical", "متغير فئوي", "Categorical Variable",
         "متغير قيمه فئات أو تسميات (ثنائي، اسمي، ترتيبي)، حتى لو خُزّن كأرقام.", "data",
         lesson="foundations.data.variable_types", related=["numerical"]),
    Term("numerical", "متغير عددي", "Numerical Variable",
         "متغير قيمه كميات قابلة للجمع والمقارنة (متصل أو منفصل).", "data",
         lesson="foundations.data.variable_types", related=["categorical"]),
    Term("time_series", "سلسلة زمنية", "Time Series",
         "قياسات مرتبة زمنيًا؛ الترتيب جزء من المعلومة.", "data", lesson="foundations.data.data_modalities",
         related=["sequence"]),
    Term("sequence", "تسلسل", "Sequence",
         "بيانات مرتبة حيث يهم ترتيب العناصر (نص، سلسلة زمنية).", "data",
         lesson="foundations.data.data_modalities", related=["time_series"]),
    Term("dtype", "نوع البيانات", "dtype",
         "نوع تخزين العنصر الواحد في المصفوفة أو الموتر (float32، int64، ...).", "data",
         lesson="foundations.data.dtype", related=["tensor", "shape"]),
    Term("tensor", "الموتر", "Tensor",
         "مصفوفة متعددة المحاور: التمثيل الأساسي للبيانات والمعلمات في أطر التعلم العميق.", "data",
         lesson="foundations.data.data_modalities", related=["shape", "rank", "dtype"]),
    Term("shape", "الشكل", "Shape",
         "قائمة بطول كل محور في المصفوفة/الموتر، مثل (n, d).", "data",
         lesson="foundations.data.shape_axis_rank", related=["axis", "rank", "dimension"]),
    Term("axis", "المحور", "Axis",
         "اتجاه واحد من اتجاهات الموتر؛ المحور 0 عادةً محور الملاحظات.", "data",
         lesson="foundations.data.shape_axis_rank", related=["shape", "batch_dimension"]),
    Term("rank", "الرتبة", "Rank (ndim)",
         "عدد محاور الموتر: 0 للعدد، 1 للمتجه، 2 للمصفوفة.", "data",
         lesson="foundations.data.shape_axis_rank", related=["shape", "dimension"]),
    Term("dimension", "البُعد", "Dimension",
         "كلمة ملتبسة: تعني أحيانًا الرتبة (عدد المحاور) وأحيانًا طول محور. في المنصة نوضح المقصود دائمًا.",
         "data", lesson="foundations.data.shape_axis_rank", related=["rank", "shape"]),
    Term("batch_dimension", "بُعد الدفعة", "Batch Dimension",
         "المحور 0 في مدخل الشبكة: عدد الملاحظات المعالجة معًا.", "data",
         lesson="foundations.data.shape_axis_rank", related=["axis", "batch"]),
    # --------------------------------------------------------------- training
    Term("epoch", "الحقبة", "Epoch",
         "مرور كامل واحد على كل بيانات التدريب.", "training",
         lesson="foundations.start.terminology_orientation", related=["batch", "iteration"]),
    Term("batch", "الدفعة", "Batch",
         "مجموعة من الملاحظات تُمرَّر عبر النموذج معًا وتُنتج تحديثًا واحدًا.", "training",
         lesson="foundations.start.terminology_orientation", related=["batch_size", "epoch"]),
    Term("batch_size", "حجم الدفعة", "Batch Size",
         "عدد الملاحظات في الدفعة الواحدة؛ معلمة فائقة.", "training",
         lesson="foundations.start.terminology_orientation", related=["batch", "hyperparameter"]),
    Term("iteration", "التكرار (الخطوة)", "Iteration / Step",
         "تحديث واحد للمعلمات على دفعة واحدة. عدد التكرارات في الحقبة = عدد الدفعات.", "training",
         lesson="foundations.start.terminology_orientation", related=["batch", "epoch"]),

    # ------------------------------------------------------- python / numpy
    Term("ndarray", "مصفوفة NumPy", "ndarray",
         "المصفوفة العددية الأساسية في NumPy: عناصر بنوع واحد مرتبة على محاور، عملياتها متجهية وسريعة.", "data",
         lesson="foundations.python.numpy_ndarray", related=["tensor", "shape", "dtype"]),
    Term("vectorization", "التوجيه المتجهي", "Vectorization",
         "كتابة العملية على المصفوفة كلها بدل حلقة على عناصرها؛ أسرع بمراتب ويسمح بالتوازي على GPU.", "data",
         lesson="foundations.python.vectorization_broadcasting", related=["broadcasting", "ndarray"]),
    Term("broadcasting", "البث", "Broadcasting",
         "قواعد تمديد المحاور ذات الطول 1 (أو المفقودة) لإجراء عملية بين شكلين مختلفين دون نسخ.", "data",
         lesson="foundations.python.vectorization_broadcasting", related=["shape", "vectorization"]),
    Term("dataframe", "إطار البيانات", "DataFrame",
         "جدول pandas ثنائي البُعد بأعمدة مسماة قد تختلف أنواعها؛ Series عمود واحد منه.", "data",
         lesson="foundations.python.pandas_basics", related=["dataset"]),
    Term("seed", "البذرة العشوائية", "Random Seed",
         "قيمة تبدأ منها خوارزمية توليد الأعداد العشوائية؛ نفس البذرة ← نفس التسلسل ← تكرارية.", "training",
         lesson="foundations.python.randomness_reproducibility", related=["reproducibility"]),
    Term("reproducibility", "التكرارية", "Reproducibility",
         "القدرة على إعادة الحصول على نفس النتيجة بنفس الكود والبيانات والبذور.", "training",
         lesson="foundations.python.randomness_reproducibility", related=["seed"]),
    # ------------------------------------------------------------------- math
    Term("function", "الدالة", "Function",
         "قاعدة تعطي لكل مدخل مخرجًا واحدًا؛ النموذج والطبقة والخسارة كلها دوال.", "math",
         lesson="foundations.math.functions", related=["model"], notation="f(x)"),
    Term("exponential", "الدالة الأسية", "Exponential (e^x)",
         "دالة موجبة دائمًا تكبر بسرعة؛ أساس Softmax.", "math", lesson="foundations.math.exponent_log",
         related=["logarithm", "softmax"], notation="e^{x}"),
    Term("logarithm", "اللوغاريتم الطبيعي", "Natural Logarithm (ln)",
         "عكس الدالة الأسية، معرّف للموجب فقط؛ −ln p هو «مفاجأة» الحدث وأساس خسائر التصنيف.", "math",
         lesson="foundations.math.exponent_log", related=["exponential", "cross_entropy"], notation=r"\ln x"),
    Term("summation", "رمز المجموع", "Summation (Σ)",
         "اختصار لجمع حدود مفهرسة؛ يقابل حلقة for أو np.sum.", "math",
         lesson="foundations.math.summation_average_abs", related=["mean"], notation=r"\sum_{i=1}^{n}"),
    Term("mean", "المتوسط", "Mean (Average)",
         "مجموع القيم مقسومًا على عددها؛ مركز الثقل.", "math", lesson="foundations.prob.descriptive",
         related=["variance", "standard_deviation"], notation=r"\mu = \frac{1}{n}\sum x_i"),
    Term("variance", "التباين", "Variance",
         "متوسط مربع البعد عن المتوسط؛ يقيس الانتشار بوحدة مربعة.", "math", lesson="foundations.prob.descriptive",
         related=["mean", "standard_deviation"], notation=r"\sigma^2"),
    Term("standard_deviation", "الانحراف المعياري", "Standard Deviation",
         "جذر التباين؛ الانتشار بنفس وحدة البيانات؛ يُستخدم في التوحيد القياسي.", "math",
         lesson="foundations.prob.descriptive", related=["variance", "standardization"], notation=r"\sigma"),
    Term("standardization", "التوحيد القياسي", "Standardization (z-score)",
         "تحويل خاصية إلى (x − μ)/σ فيصبح متوسطها 0 وانحرافها 1؛ μ وσ من بيانات التدريب فقط.", "data",
         lesson="foundations.prob.descriptive", related=["mean", "standard_deviation"]),
    # ------------------------------------------------------------- linalg
    Term("scalar", "العدد (سكالار)", "Scalar",
         "رقم واحد؛ موتر رتبة 0.", "math", lesson="foundations.linalg.scalars_vectors", related=["vector", "rank"]),
    Term("vector", "المتجه", "Vector",
         "قائمة مرتبة من الأرقام؛ موتر رتبة 1؛ كل ملاحظة وكل تدرج متجه.", "math",
         lesson="foundations.linalg.scalars_vectors", related=["scalar", "matrix", "dot_product"], notation=r"\mathbf{x}"),
    Term("norm", "المعيار (الطول)", "Norm",
         "طول المتجه: جذر مجموع مربعات مكوناته؛ معيار التدرج أداة تشخيص للتلاشي والانفجار.", "math",
         lesson="foundations.linalg.scalars_vectors", related=["vector", "gradient"], notation=r"\|\mathbf{x}\|"),
    Term("dot_product", "الضرب النقطي", "Dot Product",
         "مجموع حواصل ضرب المكونات المتقابلة لمتجهين؛ رقم واحد يقيس التوافق؛ قلب الخلية العصبية.", "math",
         lesson="foundations.linalg.dot_product", related=["vector", "matrix_multiplication"], notation=r"\mathbf{w}\cdot\mathbf{x}"),
    Term("matrix", "المصفوفة", "Matrix",
         "شبكة أرقام بصفوف وأعمدة؛ موتر رتبة 2؛ X (ملاحظات×خصائص) وW (مدخلات×وحدات).", "math",
         lesson="foundations.linalg.matrices", related=["vector", "tensor", "transpose"], notation="A"),
    Term("transpose", "المنقولة", "Transpose",
         "تبديل الصفوف بالأعمدة؛ (m, n) تصبح (n, m)؛ ليست إعادة تشكيل.", "math",
         lesson="foundations.linalg.matrices", related=["matrix"], notation=r"A^{\mathsf T}"),
    Term("matrix_multiplication", "ضرب المصفوفات", "Matrix Multiplication",
         "كل عنصر في الناتج ضرب نقطي لصف من الأولى في عمود من الثانية؛ الشرط (m,n)@(n,k)→(m,k).", "math",
         lesson="foundations.linalg.matrix_multiplication", related=["dot_product", "hadamard_product"], notation="AB"),
    Term("hadamard_product", "ضرب هادامارد (العنصري)", "Hadamard (Element-wise) Product",
         "ضرب كل عنصر في مقابله؛ يتطلب نفس الشكل؛ يظهر في البوابات والأقنعة.", "math",
         lesson="foundations.linalg.matrix_multiplication", related=["matrix_multiplication"], notation=r"A \odot B"),
    Term("identity_matrix", "مصفوفة الوحدة", "Identity Matrix",
         "آحاد على القطر وأصفار خارجه؛ محايدة في ضرب المصفوفات.", "math",
         lesson="foundations.linalg.matrix_multiplication", related=["matrix"], notation="I"),
    Term("channel_dimension", "بُعد القناة", "Channel Dimension",
         "محور القنوات اللونية في موتر الصور: آخر محور في Keras (channels_last)، الثاني في PyTorch (channels_first).", "data",
         lesson="foundations.linalg.tensors", related=["batch_dimension", "tensor"]),
    # ----------------------------------------------------------- calculus
    Term("slope", "الميل", "Slope",
         "التغير في المخرج لكل وحدة تغير في المدخل؛ ميل القاطع بين نقطتين، والمماس عند نقطة.", "math",
         lesson="foundations.calculus.change_slope", related=["derivative"], notation=r"\Delta y/\Delta x"),
    Term("derivative", "المشتقة", "Derivative",
         "ميل المماس؛ نهاية ميل القاطع عندما تقترب النقطتان؛ دالة تعطي الميل عند كل نقطة.", "math",
         lesson="foundations.calculus.derivative", related=["slope", "partial_derivative", "gradient"], notation="f'(x)"),
    Term("partial_derivative", "المشتقة الجزئية", "Partial Derivative",
         "مشتقة دالة متعددة المتغيرات بالنسبة لمتغير واحد مع تثبيت الباقي.", "math",
         lesson="foundations.calculus.partial_gradient", related=["derivative", "gradient"], notation=r"\partial L/\partial w"),
    Term("chain_rule", "قاعدة السلسلة", "Chain Rule",
         "مشتقة تركيب دوال = حاصل ضرب المشتقات المحلية؛ أساس الانتشار الخلفي.", "math",
         lesson="foundations.calculus.chain_rule", related=["derivative", "gradient", "backpropagation"]),
    Term("jacobian", "الجاكوبي", "Jacobian",
         "مصفوفة كل المشتقات الجزئية لدالة مخرجها متجه؛ للطبقة الخطية هو مصفوفة الأوزان.", "math",
         lesson="foundations.calculus.jacobian_hessian", related=["gradient", "hessian"], notation="J"),
    Term("hessian", "الهسي", "Hessian",
         "مصفوفة المشتقات الثانية؛ تصف انحناء سطح الخسارة؛ كبيرة جدًا للشبكات فتُقرَّب.", "math",
         lesson="foundations.calculus.jacobian_hessian", related=["jacobian"], notation="H"),
    # ---------------------------------------------------------- probability
    Term("probability", "الاحتمال", "Probability",
         "عدد بين 0 و1 يقيس إمكانية حدث؛ عمليًا تكرار نسبي على المدى الطويل.", "math",
         lesson="foundations.prob.distributions", related=["conditional_probability", "distribution"], notation="P(A)"),
    Term("conditional_probability", "الاحتمال الشرطي", "Conditional Probability",
         "احتمال حدث علمًا بوقوع آخر؛ المصنف يتعلم P(y | x).", "math",
         lesson="foundations.prob.distributions", related=["probability"], notation=r"P(A \mid B)"),
    Term("distribution", "التوزيع", "Distribution",
         "وصف احتمال كل قيمة ممكنة لمتغير عشوائي (برنولي، فئوي، طبيعي...).", "math",
         lesson="foundations.prob.distributions", related=["probability", "expectation"]),
    Term("expectation", "التوقّع", "Expectation",
         "المتوسط الموزون بالاحتمالات؛ متوسط العينة يقرّبه؛ الخسارة الحقيقية توقّع تقدّره الدفعة.", "math",
         lesson="foundations.prob.distributions", related=["mean", "distribution"], notation=r"\mathbb{E}[X]"),
    Term("noise", "الضوضاء", "Noise",
         "الجزء العشوائي في الهدف الذي لا تفسره الخصائص؛ لا يمكن التنبؤ به، وحفظه يعني فرط التخصيص.", "math",
         lesson="foundations.prob.distributions", related=["distribution"]),
    Term("correlation", "الارتباط", "Correlation",
         "التغاير مقسومًا على الانحرافين؛ بين −1 و1؛ يقيس العلاقة الخطية فقط وليس سببية.", "math",
         lesson="foundations.prob.correlation", related=["covariance"], notation="r"),
    Term("covariance", "التغاير", "Covariance",
         "متوسط حاصل ضرب انحرافي متغيرين عن متوسطيهما؛ إشارته اتجاه العلاقة.", "math",
         lesson="foundations.prob.correlation", related=["correlation"], notation=r"\text{cov}(x, y)"),
    Term("likelihood", "الاحتمال الأرجح", "Likelihood",
         "احتمال البيانات المشاهدة كدالة في المعلمات؛ تعظيمه = تقليل سالب لوغاريتمه = الخسارة.", "math",
         lesson="foundations.prob.likelihood", related=["probability", "log_likelihood"], notation=r"\mathcal{L}(\theta)"),
    Term("log_likelihood", "لوغاريتم الاحتمال الأرجح", "Log-Likelihood",
         "لوغاريتم الاحتمال الأرجح؛ يحوّل الضرب إلى جمع؛ سالبه مقسومًا على n هو خسارة التصنيف.", "math",
         lesson="foundations.prob.likelihood", related=["likelihood", "cross_entropy"], notation=r"\ell(\theta)"),
    Term("entropy", "الإنتروبيا", "Entropy",
         "متوسط المفاجأة لتوزيع؛ أقصاها للتوزيع المتساوي وصفر للأكيد.", "math",
         lesson="foundations.prob.entropy_cross_entropy", related=["cross_entropy"], notation="H(p)"),
    Term("cross_entropy", "الإنتروبيا المتقاطعة", "Cross-Entropy",
         "مفاجأة الحقيقة تحت توزيع النموذج؛ مع one-hot تساوي −log p̂(الفئة الصحيحة)؛ خسارة التصنيف القياسية.", "training",
         lesson="foundations.prob.entropy_cross_entropy", related=["entropy", "log_likelihood", "softmax"], notation=r"-\sum_k y_k \log \hat p_k"),
    Term("softmax", "سوفتماكس", "Softmax",
         "تحويل أرقام حرة (logits) إلى احتمالات موجبة مجموعها 1 عبر exp ثم القسمة على المجموع.", "model",
         lesson="foundations.math.exponent_log", related=["exponential", "cross_entropy"], notation=r"\frac{e^{z_k}}{\sum_j e^{z_j}}"),
    Term("backpropagation", "الانتشار الخلفي", "Backpropagation",
         "حساب تدرج الخسارة بالنسبة لكل معلمة بتطبيق قاعدة السلسلة من الخسارة إلى الخلف عبر الطبقات مع إعادة استخدام الوسائط.", "training",
         lesson="foundations.calculus.chain_rule", related=["chain_rule", "gradient"]),

    # ---------------------------------------------------------------- modules 7–23 and course weeks 8–13
    Term("supervised_learning", "التعلم المُشرف", "Supervised Learning",
         "تعلم دالة من أزواج (مدخل، هدف) موسومة؛ الانحدار والتصنيف حالتاه الرئيسيتان.", "general",
         lesson='foundations.ml.paradigms', related=['regression', 'classification', 'target']),
    Term("regression", "الانحدار", "Regression",
         "مهمة يكون هدفها عدديًا متصلًا (سعر، كمية)؛ الخسارة النموذجية MSE/MAE والمخرج بلا تنشيط.", "general",
         lesson='foundations.ml.task_types', related=['classification', 'target', 'mse']),
    Term("classification", "التصنيف", "Classification",
         "مهمة يكون هدفها فئة (ثنائية أو متعددة)؛ المخرج احتمالات والخسارة الإنتروبيا المتقاطعة.", "general",
         lesson='foundations.ml.task_types', related=['regression', 'softmax', 'cross_entropy', 'threshold']),
    Term("baseline", "خط الأساس", "Baseline",
         "أبسط تنبؤ ممكن (الفئة الغالبة، المتوسط، القيمة الأخيرة، نموذج خطي) يجب على أي نموذج التفوق عليه ليكون ذا قيمة.", "evaluation",
         lesson='foundations.ml.baseline_generalization', related=['generalization', 'accuracy']),
    Term("generalization", "التعميم", "Generalization",
         "قدرة النموذج على الأداء الجيد على بيانات لم يرها في التدريب؛ يُقاس بالفجوة بين التدريب والمحجوز.", "evaluation",
         lesson='foundations.generalization.under_overfitting', related=['overfitting', 'underfitting', 'validation_set']),
    Term("train_test_split", "تقسيم تدريب/تحقق/اختبار", "Train / Validation / Test Split",
         "فصل البيانات إلى مجموعة لتقدير المعلمات، ومجموعة لقرارات التطوير، ومجموعة تُلمس مرة واحدة للتقرير.", "data",
         lesson='foundations.prep.splitting', related=['validation_set', 'data_leakage']),
    Term("validation_set", "مجموعة التحقق", "Validation Set",
         "بيانات محجوزة أثناء التدريب لاختيار المعلمات الفائقة والعتبة والإيقاف المبكر؛ ليست للتقرير النهائي.", "data",
         lesson='foundations.prep.splitting', related=['train_test_split', 'early_stopping', 'hyperparameter']),
    Term("data_leakage", "تسريب البيانات", "Data Leakage",
         "وصول معلومات من الاختبار أو من المستقبل أو من الهدف إلى التدريب (تحجيم قبل التقسيم، خاصية مشتقة من الهدف، خلط سلسلة زمنية)؛ يعطي أرقامًا متفائلة كاذبة.", "data",
         lesson='foundations.prep.leakage', related=['train_test_split', 'standardization']),
    Term("one_hot", "الترميز الأحادي", "One-Hot Encoding",
         "تمثيل فئة اسمية بمتجه من أصفار وواحد واحد في موضع الفئة؛ يُستخدم للخصائص الفئوية وللأهداف مع categorical_crossentropy.", "data",
         lesson='foundations.prep.encoding', related=['categorical', 'cross_entropy']),
    Term("class_imbalance", "عدم توازن الفئات", "Class Imbalance",
         "تفاوت كبير في نسب الفئات (احتيال 1%)؛ يجعل الدقة مضلّلة ويستدعي الصحة/الاستدعاء/AUC وأوزان الفئات.", "data",
         lesson='foundations.prep.imbalance_augmentation', related=['accuracy', 'precision', 'recall']),
    Term("neuron", "الخلية العصبية", "Neuron / Unit",
         "وحدة تحسب مجموعًا موزونًا للمدخلات مع انحياز ثم تطبّق دالة تنشيط: a = f(wx + b).", "model",
         lesson='foundations.neuron.neuron_perceptron', related=['weight', 'bias', 'activation_function']),
    Term("activation_function", "دالة التنشيط", "Activation Function",
         "دالة غير خطية تُطبَّق عنصريًا بعد المجموع الموزون (ReLU، sigmoid، tanh…)؛ بدونها تُطوى الطبقات في طبقة خطية واحدة.", "model",
         lesson='foundations.activations.why_nonlinearity', related=['relu', 'sigmoid', 'softmax', 'neuron']),
    Term("relu", "ReLU", "ReLU (Rectified Linear Unit)",
         "max(0, z): التنشيط الافتراضي للطبقات المخفية؛ مشتقته 1 للموجب و0 للسالب (خطر الوحدات الميتة).", "model",
         lesson='foundations.activations.relu_family', related=['activation_function', 'dead_relu']),
    Term("sigmoid", "سيجمويد", "Sigmoid",
         "1/(1+e^(−z)): يحوّل رقمًا إلى (0, 1)؛ تنشيط مخرج التصنيف الثنائي؛ يتشبع ومشتقته ≤ 0.25.", "model",
         lesson='foundations.activations.sigmoid_tanh', related=['activation_function', 'logit', 'probability'], notation=r"\sigma(z)"),
    Term("dead_relu", "ReLU الميت", "Dead ReLU",
         "وحدة ReLU مدخلها سالب لكل الملاحظات فمخرجها 0 وتدرجها 0 ولا تتعلم؛ علاجها Leaky ReLU/ELU أو تهيئة وη أنسب.", "training",
         lesson='foundations.activations.derivatives_saturation_dead', related=['relu', 'vanishing_gradient']),
    Term("layer", "الطبقة", "Layer",
         "مجموعة وحدات تحوّل موترًا إلى موتر بمعلمات (Dense، Conv2D، LSTM) أو بدونها (Dropout، Flatten، Pooling).", "model",
         lesson='foundations.architecture.layers', related=['dense_layer', 'neuron', 'parameter']),
    Term("dense_layer", "الطبقة الكثيفة", "Dense (Fully Connected) Layer",
         "طبقة كل وحدة فيها متصلة بكل مدخل: a = f(xW + b) بـ in×out + out معلمة.", "model",
         lesson='foundations.architecture.depth_width_dense', related=['layer', 'matrix_multiplication', 'parameter']),
    Term("logit", "اللوجيت", "Logit",
         "الرقم الخام قبل sigmoid/softmax في طبقة المخرج؛ الخسائر «من اللوجيت» أكثر استقرارًا عدديًا.", "model",
         lesson='foundations.forward.logits_probability_threshold', related=['sigmoid', 'softmax', 'probability']),
    Term("threshold", "العتبة", "Threshold",
         "القيمة التي يتحول عندها الاحتمال إلى قرار (0.5 افتراضيًا)؛ تُختار على التحقق بحسب كلفة الخطأين.", "evaluation",
         lesson='foundations.eval.roc_auc_threshold', related=['precision', 'recall', 'probability'], notation=r"\tau"),
    Term("mse", "متوسط مربعات الخطأ", "Mean Squared Error (MSE)",
         "متوسط (ŷ − y)²؛ خسارة الانحدار القياسية؛ جذره RMSE بوحدة الهدف.", "training",
         lesson='foundations.loss.mse_mae_huber', related=['loss', 'regression'], notation=r"\frac{1}{n}\sum (\hat y_i - y_i)^2"),
    Term("stochastic_gradient_descent", "الانحدار التدرجي العشوائي", "Stochastic Gradient Descent (SGD)",
         "تحديث المعلمات عكس تدرج الخسارة المقدَّر على دفعة صغيرة بدل كل البيانات: أسرع وأكثر ضوضاء.", "training",
         lesson='foundations.optim.gd_variants', related=['gradient', 'learning_rate', 'batch', 'momentum']),
    Term("momentum", "الزخم", "Momentum",
         "تراكم أسي للتدرجات السابقة يسرّع الاتجاهات المتسقة ويخفف التذبذب؛ β ≈ 0.9.", "training",
         lesson='foundations.optim.momentum_nesterov', related=['stochastic_gradient_descent', 'adam']),
    Term("adam", "آدم", "Adam",
         "محسّن يجمع الزخم وتكييف معدل التعلم لكل معلمة (RMSprop) مع تصحيح الانحياز؛ الافتراضي الآمن بـ η = 1e-3.", "training",
         lesson='foundations.optim.rmsprop_adam', related=['momentum', 'learning_rate', 'optimizer']),
    Term("learning_rate_schedule", "جدول معدل التعلم", "Learning-Rate Schedule",
         "تغيير η أثناء التدريب (خفض عند الثبات، تناقص أسي، جيب التمام) للجمع بين سرعة البداية ودقة النهاية.", "training",
         lesson='foundations.optim.schedules_convergence', related=['learning_rate', 'adam']),
    Term("training_loop", "حلقة التدريب", "Training Loop",
         "لكل حقبة، لكل دفعة: أمامي → خسارة → خلفي → تحديث؛ ثم تحقق. مخفية في fit وصريحة في PyTorch.", "training",
         lesson='foundations.training_loop.the_loop', related=['epoch', 'batch', 'backpropagation', 'optimizer']),
    Term("overfitting", "فرط التخصيص", "Overfitting",
         "النموذج يحفظ التدريب (خسارته منخفضة) ويسوء على المحجوز (فجوة كبيرة)؛ علاجه بيانات أكثر أو تنظيم أو نموذج أصغر.", "evaluation",
         lesson='foundations.generalization.under_overfitting', related=['underfitting', 'generalization', 'regularization']),
    Term("underfitting", "قصور التعلم", "Underfitting",
         "النموذج أبسط من المسألة (أو تدريبه غير كافٍ): خسارة عالية على التدريب والتحقق معًا.", "evaluation",
         lesson='foundations.generalization.under_overfitting', related=['overfitting', 'generalization']),
    Term("regularization", "التنظيم", "Regularization",
         "كل تقنية تقيّد النموذج لتحسين التعميم: L2/اضمحلال الأوزان، L1، Dropout، الإيقاف المبكر، زيادة البيانات.", "training",
         lesson='foundations.regularization.l1_l2_weight_decay', related=['dropout', 'early_stopping', 'overfitting']),
    Term("dropout", "الإسقاط", "Dropout",
         "تصفير عشوائي لنسبة p من الوحدات أثناء التدريب فقط (مع تحجيم الباقي)؛ في الاستدلال هوية. يقلل الاعتماد المشترك.", "training",
         lesson='foundations.regularization.dropout', related=['regularization', 'overfitting']),
    Term("early_stopping", "الإيقاف المبكر", "Early Stopping",
         "إيقاف التدريب عندما يتوقف مقياس التحقق عن التحسن لعدد حقب (patience) واسترجاع أفضل أوزان.", "training",
         lesson='foundations.regularization.early_stopping', related=['validation_set', 'overfitting', 'epoch']),
    Term("batch_normalization", "تطبيع الدفعة", "Batch Normalization",
         "طبقة تطبّع كل خاصية على الدفعة (متوسط 0 وانحراف 1) ثم تعيد التحجيم بـ γ وβ متعلَّمتين؛ تستخدم المتوسطات المتحركة في الاستدلال.", "model",
         lesson='foundations.regularization.batch_normalization', related=['standardization', 'regularization']),
    Term("data_augmentation", "زيادة البيانات", "Data Augmentation",
         "توليد أمثلة تدريب جديدة بتحويلات تحفظ الوسم (إزاحة، قلب، ضوضاء)؛ على التدريب فقط.", "training",
         lesson='foundations.regularization.augmentation_simplification', related=['regularization', 'overfitting']),
    Term("vanishing_gradient", "تلاشي التدرج", "Vanishing Gradient",
         "انكماش التدرج أسيًا عبر طبقات كثيرة أو خطوات زمنية كثيرة (مشتقات ≤ 1 وأوزان صغيرة) فلا تتعلم الطبقات الأولى/الماضي البعيد.", "training",
         lesson='foundations.backprop.backpropagation.vanishing_exploding', related=['exploding_gradient', 'relu', 'lstm']),
    Term("exploding_gradient", "انفجار التدرج", "Exploding Gradient",
         "نمو التدرج أسيًا عبر الطبقات/الزمن حتى nan؛ يُعالج بقصّ التدرج وη أصغر وتطبيع.", "training",
         lesson='foundations.backprop.backpropagation.vanishing_exploding', related=['vanishing_gradient', 'gradient_clipping']),
    Term("gradient_clipping", "قصّ التدرج", "Gradient Clipping",
         "تحديد معيار أو قيمة التدرج بحد أقصى قبل التحديث (clipnorm/clipvalue) لمنع الانفجار.", "training",
         lesson='foundations.backprop.backpropagation.debugging', related=['exploding_gradient']),
    Term("accuracy", "الدقة", "Accuracy",
         "نسبة التنبؤات الصحيحة؛ مضلّلة مع فئات غير متوازنة.", "evaluation",
         lesson='foundations.eval.classification_metrics', related=['precision', 'recall', 'confusion_matrix', 'baseline']),
    Term("precision", "الصحة", "Precision",
         "TP / (TP + FP): من كل ما تنبأنا بأنه إيجابي، كم كان صحيحًا.", "evaluation",
         lesson='foundations.eval.classification_metrics', related=['recall', 'f1_score', 'threshold']),
    Term("recall", "الاستدعاء", "Recall",
         "TP / (TP + FN): من كل الإيجابيات الحقيقية، كم التقطنا.", "evaluation",
         lesson='foundations.eval.classification_metrics', related=['precision', 'f1_score', 'threshold']),
    Term("f1_score", "مقياس F1", "F1 Score",
         "المتوسط التوافقي للصحة والاستدعاء؛ مفيد مع عدم التوازن عندما يهم الاثنان.", "evaluation",
         lesson='foundations.eval.classification_metrics', related=['precision', 'recall']),
    Term("confusion_matrix", "مصفوفة التباس", "Confusion Matrix",
         "جدول الحقيقي × المتنبأ (TN, FP, FN, TP للثنائي)؛ منه تُشتق كل مقاييس التصنيف.", "evaluation",
         lesson='foundations.eval.classification_metrics', related=['accuracy', 'precision', 'recall']),
    Term("roc_auc", "منحنى ROC والمساحة تحته", "ROC Curve & AUC",
         "ROC: الاستدعاء مقابل معدل الإنذار الكاذب لكل العتبات؛ AUC = احتمال ترتيب إيجابي فوق سلبي؛ مستقل عن العتبة.", "evaluation",
         lesson='foundations.eval.roc_auc_threshold', related=['threshold', 'recall']),
    Term("framework", "إطار العمل", "Deep Learning Framework",
         "برمجية تقدّم موترات على CPU/GPU، اشتقاقًا تلقائيًا، طبقات ونماذج، خسائر ومحسّنات، وأدوات تدريب وحفظ (TensorFlow، PyTorch).", "frameworks",
         lesson='foundations.frameworks.from_python_to_framework', related=['keras', 'tensorflow', 'pytorch', 'autodiff']),
    Term("keras", "Keras", "Keras",
         "واجهة عليا للتعلم العميق: Layers → Model → compile → fit → evaluate/predict → save؛ في هذا المقرر بخلفية TensorFlow.", "frameworks",
         lesson='foundations.frameworks.keras', related=['framework', 'tensorflow', 'fit']),
    Term("tensorflow", "TensorFlow", "TensorFlow",
         "إطار تعلم عميق: tf.Tensor، tf.Variable، GradientTape، tf.data، الأجهزة، الحفظ؛ الخلفية التي تشغّل Keras في المقرر.", "frameworks",
         lesson='foundations.frameworks.tensorflow', related=['framework', 'keras', 'gradient_tape']),
    Term("pytorch", "PyTorch", "PyTorch",
         "إطار تعلم عميق بحلقة تدريب صريحة: torch.Tensor، Autograd، nn.Module، torch.optim، DataLoader.", "frameworks",
         lesson='foundations.frameworks.pytorch', related=['framework', 'autodiff', 'training_loop']),
    Term("autodiff", "الاشتقاق التلقائي", "Automatic Differentiation",
         "حساب التدرجات آليًا بتطبيق قاعدة السلسلة على العمليات المسجلة (GradientTape في TensorFlow، Autograd في PyTorch).", "frameworks",
         lesson='foundations.frameworks.tensorflow.gradient_tape', related=['backpropagation', 'gradient_tape', 'chain_rule']),
    Term("gradient_tape", "شريط التدرج", "GradientTape",
         "سياق في TensorFlow يسجّل العمليات على المتغيرات ثم يحسب التدرج بـ tape.gradient(loss, vars).", "frameworks",
         lesson='foundations.frameworks.tensorflow.gradient_tape', related=['autodiff', 'tensorflow']),
    Term("fit", "fit", "model.fit()",
         "دالة Keras التي تنفذ حلقة التدريب كاملة (دفعات، حقب، أمامي، خسارة، اشتقاق، تحديث، مقاييس، تحقق) وتعيد History.", "frameworks",
         lesson='foundations.frameworks.keras.fit', related=['keras', 'training_loop', 'epoch', 'batch_size']),
    Term("callback", "دالة الاستدعاء (Callback)", "Callback",
         "كائن تستدعيه fit عند أحداث الحلقة (نهاية حقبة/دفعة): EarlyStopping، ModelCheckpoint، ReduceLROnPlateau، TensorBoard.", "frameworks",
         lesson='foundations.frameworks.keras.callbacks_saving', related=['fit', 'early_stopping']),
    Term("state_dict", "قاموس الحالة", "state_dict",
         "قاموس PyTorch {اسم المعلمة: موتر} لحفظ وتحميل أوزان النموذج (والمحسّن) مع الاحتفاظ بالكود للبنية.", "frameworks",
         lesson='foundations.frameworks.pytorch.saving_errors', related=['pytorch']),
    Term("zero_grad", "تصفير التدرجات", "optimizer.zero_grad()",
         "مسح .grad المتراكم في PyTorch قبل backward؛ بدونه تُجمع تدرجات كل الدفعات السابقة.", "frameworks",
         lesson='foundations.frameworks.pytorch.zero_grad', related=['pytorch', 'gradient', 'training_loop']),
    Term("gpu", "معالج الرسوميات", "GPU",
         "مسرّع بآلاف الأنوية البسيطة ينفذ ضرب المصفوفات والالتفاف بالتوازي؛ يغيّر السرعة لا الرياضيات؛ ذاكرته VRAM محدودة.", "frameworks",
         lesson='course.w13.cpu_gpu_memory', related=['batch_size', 'oom']),
    Term("oom", "نفاد الذاكرة", "Out of Memory (OOM)",
         "خطأ عندما لا تتسع ذاكرة GPU للمعلمات والتنشيطات؛ العلاج الأول تقليل حجم الدفعة ثم الدقة المختلطة.", "frameworks",
         lesson='course.w13.colab_runtime', related=['gpu', 'batch_size']),
    Term("convolution", "الالتفاف", "Convolution",
         "تمرير نواة صغيرة على الصورة وحساب مجموع الضرب العنصري عند كل موضع؛ ينتج خريطة خصائص بمعلمات مشتركة.", "model",
         lesson='course.w08.convolution', related=['kernel', 'feature_map', 'cnn']),
    Term("kernel", "النواة / المرشّح", "Kernel / Filter",
         "مصفوفة أوزان صغيرة (3×3 مثلًا) متعلَّمة تكشف نمطًا محليًا؛ k²·C_in + 1 معلمة مهما كان حجم الصورة.", "model",
         lesson='course.w08.convolution', related=['convolution', 'feature_map']),
    Term("feature_map", "خريطة الخصائص", "Feature Map",
         "مخرج تطبيق نواة واحدة على الصورة: قيمة لكل موضع تعبّر عن قوة النمط هناك.", "model",
         lesson='course.w08.convolution', related=['convolution', 'kernel']),
    Term("padding", "الحشو", "Padding",
         "إضافة أصفار حول الصورة كي تصل النواة إلى الحواف؛ same يحفظ الحجم وvalid لا يحشو.", "model",
         lesson='course.w08.padding_stride_pooling', related=['stride', 'convolution']),
    Term("stride", "الخطوة", "Stride",
         "عدد البكسلات التي تقفزها النواة بين موضعين؛ s = 2 يقلّص خريطة الخصائص إلى النصف تقريبًا.", "model",
         lesson='course.w08.padding_stride_pooling', related=['padding', 'pooling']),
    Term("pooling", "التجميع", "Pooling",
         "استبدال كل نافذة (2×2) بقيمتها القصوى أو متوسطها: تقليص بلا معلمات وثبات للإزاحات الصغيرة.", "model",
         lesson='course.w08.padding_stride_pooling', related=['stride', 'cnn']),
    Term("cnn", "الشبكة الالتفافية", "Convolutional Neural Network (CNN)",
         "شبكة من كتل [التفاف + تنشيط + تجميع] ثم رأس كثيف؛ تستغل محلية الصور ومشاركة الأوزان.", "model",
         lesson='course.w08.layers_shapes', related=['convolution', 'pooling', 'feature_map']),
    Term("timestep", "الخطوة الزمنية", "Timestep",
         "موضع في التسلسل؛ النافذة من T خطوة هي الملاحظة بشكل (samples, timesteps, features).", "data",
         lesson='course.w10.sequences_hidden_state', related=['sequence', 'hidden_state']),
    Term("hidden_state", "الحالة المخفية", "Hidden State",
         "متجه h_t يلخّص التسلسل حتى الخطوة t ويعود مدخلًا في الخطوة التالية: ذاكرة الشبكة التكرارية.", "model",
         lesson='course.w10.sequences_hidden_state', related=['rnn', 'timestep', 'lstm'], notation=r"h_t"),
    Term("rnn", "الشبكة التكرارية", "Recurrent Neural Network (RNN)",
         "خلية واحدة بأوزان مشتركة تُطبَّق على كل خطوة زمنية وتحمل حالة مخفية: h_t = tanh(x_t Wx + h_{t−1} Wh + b).", "model",
         lesson='course.w10.sequences_hidden_state', related=['hidden_state', 'bptt', 'lstm', 'gru']),
    Term("bptt", "النشر عبر الزمن", "Backpropagation Through Time (BPTT)",
         "الانتشار الخلفي على الشبكة التكرارية المنشورة عبر T خطوة مع جمع تدرجات الأوزان المشتركة؛ مصدر التلاشي/الانفجار عبر الزمن.", "training",
         lesson='course.w10.rnn_bptt_vanishing', related=['rnn', 'backpropagation', 'vanishing_gradient']),
    Term("lstm", "الذاكرة طويلة قصيرة المدى", "LSTM",
         "خلية تكرارية بحالة خلية تمر بجمع وثلاث بوابات (نسيان، إدخال، إخراج) تتعلم متى تنسى وتكتب وتكشف؛ تعالج تلاشي التدرج.", "model",
         lesson='course.w11.cell_gates_equations', related=['rnn', 'gru', 'gate', 'vanishing_gradient']),
    Term("gru", "الوحدة التكرارية ذات البوابات", "GRU",
         "تبسيط لـ LSTM ببوابتين (تحديث، إعادة ضبط) وحالة واحدة؛ معلمات أقل وأداء مماثل غالبًا.", "model",
         lesson='course.w12.update_reset_gates', related=['lstm', 'rnn', 'gate']),
    Term("gate", "البوابة", "Gate",
         "متجه بقيم sigmoid في (0, 1) يضرب عنصريًا معلومة ليقرر كم يمر منها (نسيان/إدخال/إخراج في LSTM، تحديث/إعادة ضبط في GRU).", "model",
         lesson='course.w11.cell_gates_equations', related=['lstm', 'gru', 'sigmoid']),
    Term("embedding", "التضمين", "Embedding",
         "طبقة تحوّل رمز فئوي (كلمة) إلى متجه كثيف متعلَّم؛ الطبقة الأولى في نماذج النصوص.", "model",
         lesson='course.w12.applications', related=['sequence', 'one_hot']),
]
